[package]
name = "left_right_rw_lock"
version = "0.1.0"
authors = ["Max Galkin <maksim.galkin@gmail.com>"]
repository = "https://github.com/yacoder/left-right-rwlock-rust"
readme = "README.md"
keywords = ["concurrency", "wait-free"]
license = "MIT"

[dependencies]

